# Generated by Django 5.2.4 on 2025-07-29 18:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefone', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Processo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=50, unique=True)),
                ('descricao', models.TextField()),
                ('data_abertura', models.DateField(auto_now_add=True)),
                ('status', models.CharField(default='aberto', max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='processos', to='processos.cliente')),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=100)),
                ('tipo', models.CharField(choices=[('reuniao', 'Reunião com cliente'), ('audiencia', 'Audiência'), ('prazo', 'Prazo Processual'), ('documento', 'Envio de Documentação'), ('consultoria', 'Consultoria Jurídica'), ('outro', 'Outro')], max_length=150)),
                ('data', models.DateTimeField()),
                ('local', models.CharField(blank=True, max_length=100, null=True)),
                ('descricao', models.TextField(blank=True, null=True)),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atividades', to='processos.processo')),
            ],
        ),
        migrations.CreateModel(
            name='TransacaoFinanceira',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.DateField(auto_now_add=True)),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10)),
                ('situacao', models.CharField(choices=[('pago', 'Pago'), ('pendente', 'Pendente'), ('cancelado', 'Cancelado'), ('reembolsado', 'Reembolsado')], max_length=20)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='processos.cliente')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacoes', to='processos.processo')),
            ],
        ),
    ]
