# Generated by Django 6.0.6 on 2026-06-08 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('processos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='evento',
            options={'ordering': ['data']},
        ),
        migrations.RemoveField(
            model_name='transacaofinanceira',
            name='cliente',
        ),
        migrations.AddField(
            model_name='processo',
            name='tipo',
            field=models.CharField(choices=[('civil', 'Cível'), ('criminal', 'Criminal'), ('trabalhista', 'Trabalhista'), ('familia', 'Família'), ('constitucional', 'Constitucional'), ('tributario', 'Tributário'), ('outro', 'Outro')], default='civil', max_length=30),
        ),
        migrations.AddField(
            model_name='processo',
            name='valor',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AlterField(
            model_name='evento',
            name='tipo',
            field=models.CharField(choices=[('reuniao', 'Reunião com cliente'), ('audiencia', 'Audiência'), ('prazo', 'Prazo Processual'), ('documento', 'Envio de Documentação'), ('consultoria', 'Consultoria Jurídica'), ('outro', 'Outro')], max_length=100),
        ),
        migrations.AlterField(
            model_name='evento',
            name='titulo',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='processo',
            name='status',
            field=models.CharField(choices=[('aberto', 'Aberto'), ('encerrado', 'Encerrado'), ('arquivado', 'Arquivado'), ('suspenso', 'Suspenso')], default='aberto', max_length=20),
        ),
    ]
